### ISSUE TITLE
3 icons with invalid fill

### ISSUE THREAD

**Issue by cyberalien** [tabler/tabler-icons#304]
3 icons have `fill="#D8D8D8"` for shapes, where it isn't needed:
- icons/brand-monday.svg
- icons/brand-react.svg
- icons/chess.svg

In all 3 icons it doesn't really affect anything because those shapes either have stroke wider than fill or aren't closed so there is no fill, but still I think this is a bug.

If it does have purpose, it is also bad because using almost white color where it is meant to be transparent, means icons would look incorrect on dark backgrounds.

**Comment by codecalm** [comment]
oh, yeah, sorry for my bad. I've fixed it, I'll release fixed package soon :) 

Thank you! :)

**Comment by cyberalien** [comment]
Issue is back after last update and `brand-redux.svg` joins the party with not one, but 3 shapes that use white fill.

**Comment by codecalm** [comment]
I've added rule to importer, so from now it shouldn't be repeated :)
